### ISSUE TITLE
Just for clarity sake, how would I find the game build number myself?

### ISSUE THREAD

**Issue by korewatori** [Sainan/GTA-V-Decompiled-Scripts#1]
```Download the background script from http://prod.cloud.rockstargames.com/titles/gta5/pcros/bgscripts/bg_ng_xxxx_y.rpf where xxxx_y equals your the game build, e.g. bg_ng_2372_0.rpf for build 2372, and extract "valentinerpreward2" via OpenIV.```

say, what would the latest update (Los Santos Tuners) be and how would I find that out for myself?

Thanks!

**Comment by BitDEVil2K16** [comment]
Fileversion from gta5.exe

**Comment by Sainan** [comment]
Personally, I would scan for `4C 8D 05 ? ? ? ? 48 8D 15 ? ? ? ? 48 8B C8 E8 ? ? ? ? 48 8D 15 ? ? ? ? 48 8D 4C 24 20 E8` in IDA to find the game build version and Online version. You would also see it in the bottom right when the game starts up  (without any mods that shorten the sequence). That file version solution is very elegant, tho.
