### ISSUE TITLE
1.57?

### ISSUE THREAD

**Issue by SecuritySlayer** [Sainan/GTA-V-Decompiled-Scripts#4]
You posted the 1.57 ver before. Where can i find it?

**Comment by Sainan** [comment]
🙃 
![image](https://user-images.githubusercontent.com/63328889/147788590-d835a823-a327-47b6-9919-e5ff89b68510.png)

**Comment by SecuritySlayer** [comment]
> 🙃 ![image](https://user-images.githubusercontent.com/63328889/147788590-d835a823-a327-47b6-9919-e5ff89b68510.png)

Yes i saw that :)
Just idk how i look on google they don't tell the way to see like freemode.c

**Comment by Sainan** [comment]
https://github.com/Sainan/GTA-V-Decompiled-Scripts/commit/a37acaf2db54bb1b2b3c02803d4305bb8718d339
